### ISSUE TITLE
Custom keywords not working

### ISSUE THREAD

**Issue by PaulVanSchayck** [brpaz/ulauncher-jetbrains#6]
Nice extension!

Got the following error when setting a custom keyword.
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/paul/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-jetbrains/main.py", line 58, in on_event
    file_path = extension.get_recent_projects_file_path(keyword)
  File "/home/paul/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-jetbrains/main.py", line 34, in get_recent_projects_file_path
    raise AttributeError("Invalid keyword detected")
AttributeError: Invalid keyword detected
```
Looking at the code, there seems to be an overlook here to support custom keywords.

**Comment by pwnyprod** [comment]
image grabber etc needs to be refactored, i try to refactor this too if you dont mind :smile:
